version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:1.6
    container_name: brokerService
    volumes:
    - ./mqtt/:/mosquitto/config/
    ports:
    - "9001:9001"
    - "1883:1883"
    restart: always